### ISSUE TITLE
mkexp.py does not generate a complete ocnconf.yaml

### ISSUE THREAD

**Issue by sshakoor1** [GEOS-ESM/GEOS_Util#145]
When trying to generate coupled diagnostics with `mkplots.py`, we first need to generate a `ocnconf.yaml` from `mkexp.py`. However the yaml file created from `mkexp.py` is incredibly barebones, and you will need to manually add your `griddir` and plotset entries (e.i. sst, sss, ssh)

Running a command like `python mkexp.py myexperiment --datadir path/to/myexperiment` will generate a yaml file that looks like this:
```
# Auto generated by mkexp.py
expid:     myexperiment

# You can list experimants to compare following the pattern below
#cmpexp:
#    - path_to_config_file1
#    - path_to_config_file2

data_path: path/to/myexperiment
plot_path: /home/sshakoor/geos5/plots_ocn

# You can specify dates interval to be used for analysis
# following the pattern below
#dates: ['yyyy-mm-dd','yyyy-mm-dd']
```

When really it seems like it would make more sense to auto-generate plotsets and the griddir unless otherwise specified. For example something like this from that same command would be ideal:
```
# Auto generated by mkexp.py
expid:     myexperiment

# You can list experimants to compare following the pattern below
#cmpexp:
#    - path_to_config_file1
#    - path_to_config_file2

data_path: path/to/myexperiment
plot_path: /home/sshakoor/geos5/plots_ocn
griddir: /discover/nobackup/projects/gmao/ssd/aogcm/ocean_bcs/MOM5/1440x1080

# You can specify dates interval to be used for analysis
# following the pattern below
#dates: ['yyyy-mm-dd','yyyy-mm-dd']
plots:
  plotsets: [sst, sss, ssh]

  SST:
    colname: geosgcm_ocn2dT
    name: TS
    coltype: GEOSTripolar
    template: '{data_path}/geosgcm_ocn2dT/{expid}.{colname}.monthly.??????.nc4'

  SSS:
    colname: geosgcm_ocn2dT
    name: SSS
    coltype: GEOSTripolar
    template: '{data_path}/geosgcm_ocn2dT/{expid}.{colname}.monthly.??????.nc4'

  SSH:
    colname: geosgcm_ocn2dT
    name: ETAN
    coltype: GEOSTripolar
    template: '{data_path}/geosgcm_ocn2dT/{expid}.{colname}.monthly.??????.nc4'
```

Not a pressing issue but it would be a nice feature to include, as the current way of manually adding these entries is very unintuitive if you're not already familiar with the structure of these scripts.
